# Based on a file from https://github.com/mikenikles/cypress-on-gitpod with custom changes.
# Licensed under the MIT license.

image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      yarn
      gp sync-done install
    command: yarn dev
  - init: gp sync-await install
    command: yarn cypress
  - command: git branch
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore
