name: Add to project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add labeled issues to general project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@31b3f3ccdc584546fc445612dec3f38ff5edb41c # v0.5.0
        with:
          project-url: https://github.com/orgs/octoclairvoyant/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug, enhancement, chore
          label-operator: OR
