name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: Check types
        run: yarn type-check
      - name: Lint code base
        run: yarn lint
      - name: Check code base formatting
        run: yarn format:check
        env:
          CI: true
