name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: ESLint
        run: npm run lint

  types_check:
    name: Types Check
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: Check codebase types
        run: npm run type-check
      - name: Check Cypress types
        run: npm run type-check:cypress

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: Prettier
        run: npm run format:check

  tests:
    name: Unit & Integration tests
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: Run jest
        run: npm run test:ci

  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]

    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - name: Setup Node.js
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: Run Cypress tests
        uses: cypress-io/github-action@fbae4a1470a4ec5295130bc9dd7d8bd1b7c545c0
        with:
          install: false
          build: npm run build
          start: npm run serve
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
          group: merge
          # tag will be either "push" or "pull_request"
          tag: ${{ github.event_name }}
          command-prefix: 'percy exec -t 350 -- npx'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # - if the event is push, the title will be undefined
          # and Cypress will get the commit message from Git information
          # - if the event is pull_request, then we set the commit
          # message to the pull request title
          # https://github.com/cypress-io/github-action/issues/124#issuecomment-653180260
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}

          # Percy config
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_TARGET_BRANCH: 'main'
          PERCY_BRANCH: ${{ github.head_ref }}
