name: CI

on:
  pull_request:
    branches: [main]
  merge_group:

permissions:
  contents: read
  actions: write
  checks: write

env:
  # Skip Cypress installation in the whole workflow, not necessary here
  CYPRESS_INSTALL_BINARY: 0

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  code_validation:
    strategy:
      fail-fast: false
      matrix:
        validation_script:
          [
            'lint',
            'type-check',
            'type-check:cypress',
            'format:check',
            'test:ci',
          ]
    name: 'Code Validation: ${{ matrix.validation_script }}'
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      # Act
      - name: Run script
        run: pnpm ${{ matrix.validation_script }}
