name: CI

on:
  pull_request:
    branches: [main]
  merge_group:

permissions:
  contents: read
  actions: write
  checks: write

env:
  # Skip Cypress installation in the whole workflow, not necessary here
  CYPRESS_INSTALL_BINARY: 0

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  code_validation:
    strategy:
      fail-fast: false
      matrix:
        validation_script:
          [
            'lint',
            'type-check',
            'type-check:cypress',
            'format:check',
            'test:ci',
          ]
    name: 'Code Validation: ${{ matrix.validation_script }}'
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      # Act
      - name: Run script
        run: pnpm ${{ matrix.validation_script }}

      - name: Upload coverage reports
        if: matrix.validation_script == 'test:ci'
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457 # v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
