name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

env:
  # Skip Cypress installation in the whole workflow, not necessary here
  CYPRESS_INSTALL_BINARY: 0

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7 # tag=0.10.0
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Act
      - name: ESLint
        run: pnpm lint

  types_check:
    name: Types Check
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7 # tag=0.10.0
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Act
      - name: Check codebase types
        run: pnpm type-check
      - name: Check Cypress types
        run: pnpm type-check:cypress

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7 # tag=0.10.0
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Act
      - name: Prettier
        run: pnpm format:check

  tests:
    name: Unit & Integration tests
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7 # tag=0.10.0
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Act
      - name: Run jest
        run: pnpm test:ci
