name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: Setup Node.js
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: ESLint
        run: npm run lint

  types_check:
    name: Types Check
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: Setup Node.js
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: Check codebase types
        run: npm run type-check
      - name: Check Cypress types
        run: npm run type-check:cypress

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: Setup Node.js
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: Prettier
        run: npm run format:check

  tests:
    name: Unit & Integration tests
    runs-on: ubuntu-latest
    steps:
      # Arrange
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: Setup Node.js
        uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # tag=v3.1.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      # Act
      - name: Run jest
        run: npm run test:ci
