name: CI

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - uses: octoclairvoyant/octoclairvoyant-webapp/.github/workflows/setup.yml@main
      - name: ESLint
        run: yarn lint

  types_check:
    name: Types Check
    runs-on: ubuntu-latest
    steps:
      - uses: octoclairvoyant/octoclairvoyant-webapp/.github/workflows/setup.yml@main
      - name: Check types
        run: yarn type-check

  format_check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: octoclairvoyant/octoclairvoyant-webapp/.github/workflows/setup.yml@main
      - name: Prettier
        run: yarn format:check

  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]

    steps:
      - uses: octoclairvoyant/octoclairvoyant-webapp/.github/workflows/setup.yml@main
      - name: Run Cypress tests
        uses: cypress-io/github-action@a69c39e3d674805c4e0f3bb8a94222c97f48815a
        with:
          install: false
          build: yarn build
          start: yarn serve
          wait-on: 'http://localhost:3000'
          record: true
          parallel: true
          group: merge
          # tag will be either "push" or "pull_request"
          tag: ${{ github.event_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          # - if the event is push, the title will be undefined
          # and Cypress will get the commit message from Git information
          # - if the event is pull_request, then we set the commit
          # message to the pull request title
          # https://github.com/cypress-io/github-action/issues/124#issuecomment-653180260
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
