name: Setup

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '14'

jobs:
  setup:
    name: Setup job
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # renovate: tag=v0.9.1
      - name: Checkout repository
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2.3.5
      - name: Setup Node.js v${{ inputs.node-version }}
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2.4.1
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
